forvalues ii = 2008(1)2011{
use "E:/企业数据/税调数据(团队数据)/1 原始数据_税收调查数据2007-2016/税调`ii'新.dta" ,clear
keep id year qymc hylb dqdm zzs_xse zzs_jyxse zzs_mzxse zzs_jzjtxse zzs_xxse zzs_xxse17 zzs_xxse13 zzs_jxse zzs_jxse17 zzs_jxse17gcsb zzs_jxse17dk zzs_jxse17jksb zzs_jxse13 zzs_jxse13dk zzs_jxse13ncpdk zzs_jxse6 zzs_jxszce zzs_qcld zzs_ydkhj zzs_qmlddqse zzs_sjdk zzs_jyyns zzs_mzyns zzs_yns zzs_yjcb zzs_ncwj zzs_ncyqwj zzs_yn zzs_bdyn zzs_qj zzs_yncb zzs_ydyn zzs_nmwj zzs_nmyqwj zzs_cbdldse zzs_ldjxse zzs_hdse zzs_jzjt zzckts_xse zzckts_msxse zzckts_sbmsxse zzckts_mdtse zzckts_mdtsdje zzckts_tse zzckts_ytse zzckts_mdse zzckts_ncytwtse zzckts_sjtse zzckts_nmytwte zzckts_stxfse zzckts_bsjke zzckts_bscke zzckts_tqbscke zzckts_zrhw zzckts_zchw zzckts_nxhw zzckts_nxbslx zzckts_gclj zzckts_llgjf zzckts_hwjke zzckts_ynjkzzs zzckts_ynjkxfs zzckts_ynjkgs zzckts_ynckgs xfs_xse xfs_nxmzxse xfs_ckmzxse xfs_jzyj xfs_dk xfs_jz xfs_yj xfs_cjyj xfs_yjdkdj xfs_yjcb xfs_ncwj xfs_ncyqwj xfs_yn xfs_bdyn xfs_yndkdj xfs_qj xfs_yncb xfs_ydyn xfs_nmwj xfs_nmyqwj yys_jzsr yys_bdjzsr yys_ydjzsr yys_kcyye yys_ysyye yys_msyye yys_jm yys_yj yys_yjdkdj yys_yjcb yys_ncwj yys_yqwj yys_yn yys_bdyn yys_yndkdj yys_qj yys_yncb yys_ydyn yys_nmwj yys_nmyqwj fcs_mj fcs_jsfcyzzy fcs_zyjsyzhj fcs_zysl fcs_zyjmse fcs_zyyjse fcs_zyynse fcs_czzjsr fcs_czzfzjsr fcs_czjmse fcs_czyjse fcs_czynse cztdsys_mj cztdsys_ysmj cztdsys_jmse cztdsys_yjse cztdsys_ynse ccs_cycyjse ccs_sycyjse ccs_mtcyjse ccs_qtclyjse ccs_cbyjse ccs_jmse ccs_yjse ccs_ynse ccs_yndkdjse tdzzs_zrmj tdzzs_yjyjse tdzzs_ynyjse tdzzs_zrfdcsr tdzzs_zrptzfsr tdzzs_kchj tdzzs_ftdsyqje tdzzs_fkfcb tdzzs_fkffy tdzzs_fzrfdcsj tdzzs_fqtkc tdzzs_tdsyqje tdzzs_jfpgj tdzzs_zrsj tdzzs_zze tdzzs_zzebkcje tdzzs_jmse tdzzs_yjse tdzzs_ynse gds_ysmj gds_gdmj gds_qtmj gds_jmse gds_yjse gds_ynse gds_cjjghj gds_tdjyjg gds_fwjyjg gds_jmqsse gds_yjqsse gds_ynqsse dfs_yjzys dfs_yjcsjss dfs_yjyys dfs_ynzys dfs_yncsjss dfs_yngrsds dfs_yndkdjgrsds dfs_yndkdjlxsds dfs_qyyngrsds dfs_ynyhs dfs_dkdjyhs dfs_ynyys dfs_ynclgzs dfs_yjxzsf dfs_yjjyfj dfs_yjwhjs dfs_ynxzsf dfs_ynjyfj dfs_ynwhjs dfs_ynshbx dfs_ynqt dfs_ynfk sds_yysr sds_yycb sds_yysjjfj sds_xsfy sds_glfy sds_cwfy sds_zcjzss sds_gyjzbdjsy sds_tzsy sds_yylr sds_yywsr sds_yywzc sds_lrze sds_nstzzje sds_nstzjse sds_jwmbjn sds_nstzsd sds_mbyqks sds_ynssde sds_sl25 sds_yjsdse sds_jmsdse sds_xwqy sds_gxqy sds_mzqydfs sds_gdqyh sds_qt sds_dmsdse sds_yjse sds_jwyj sds_jwdm sds_sjyjsdse sds_sjyjse sds_ybse sds_djdje sds_wjrke sds_yqwje sds_jzjtse sds_srsrze sds_srsl sds_sryj sds_cbcbze sds_cbsl sds_cbyj sds_yjsl sds_yjyjse sds_yjyjsdse sds_yjybse sds_fzftyjse3 sds_sjjnyjse3 sds_jdsjjne4 lrb_yysr lrb_zysr lrb_qtsr lrb_yycb lrb_zycb lrb_qtcb lrb_yysjfj lrb_xsfy lrb_glfy lrb_xcpfy lrb_zdfy lrb_cwfy lrb_zcjzss lrb_gyjzjsy lrb_tzsy lrb_hytzsy lrb_yylr lrb_yywsr lrb_btsr lrb_yywzc lrb_gyjzzc lrb_lrze lrb_sdsfy lrb_jlr lrb_kfplr lrb_gdfplr lrb_wfplr zcb_zcncs zcb_cldzc zcb_chbzj zcb_cyszk zcb_cch zcb_cycl zcb_cfldzc zcb_cgdzc zcb_zcnms zcb_mldzc zcb_mhbzj zcb_myszk zcb_mch zcb_mycl zcb_mfldzc zcb_mgdzc zcb_mgdzcyz zcb_mljzj zcb_mgdzcjz zcb_fzncs zcb_cldfz zcb_cyfzk zcb_cfldfz zcb_ccqjk zcb_fznms zcb_mldfz zcb_myfzk zcb_mfldfz zcb_mcqjk zcb_qyncs zcb_qynms zcb_sszbnms zcb_zbgjnms xjb_xjlr xjb_xsxj xjb_sffh xjb_xjlc xjb_gmsp xjb_zfzg xjb_zfzzs xjb_zfsds xjb_zfqt xjb_jyxj xjb_tzxj xjb_czxj xjb_hlbd xjb_xjzje qt_wgsb qt_rzzlsb qt_wgbdc qt_rzzlbdc qt_zjgdzc qt_zjjygdzc qt_zjjyfw qt_zjjksb qt_nmjygdzcjz qt_jyfwjz qt_jyjksbjz qt_grsblw qt_jtzj qt_sbjtzj qt_fwjtzj qt_wghw qt_wgryf qt_wgjgf qt_wgxlf qt_wgysf qt_wgyff qt_wgxxfw qt_wgwhcy qt_ggzc qt_sjfwzc qt_wlfwzc qt_wggkfw qt_wgjcfw qt_wghwys qt_cc qt_wgyxdcfw qt_wgzxfw qt_wgjzlwzc qt_jzaz qt_xszs qt_qtgczy qt_wgzgpxf qt_clzc qt_qtzc qt_lxzzc qt_jtgzjj qt_nczgs qt_nmzgs qt_zcz qt_zjz qt_dlxfl qt_mtxfl qt_yxfl qt_sxfl 
ren zzs_xse zzs_xse
ren zzs_jyxse zzs_jyxse
ren zzs_mzxse zzs_mzxse
ren zzs_jzjtxse zzs_jzjtxse
ren zzs_xxse zzs_xxse
ren zzs_xxse17 zzs_xxse17
ren zzs_xxse13 zzs_xxse13
ren zzs_jxse zzs_jxse
ren zzs_jxse17 zzs_jxse17
ren zzs_jxse17gcsb zzs_jxse17gcsb
ren zzs_jxse17dk zzs_jxse17dk
ren zzs_jxse17jksb zzs_jxse17jksb
ren zzs_jxse13 zzs_jxse13
ren zzs_jxse13dk zzs_jxse13dk
ren zzs_jxse13ncpdk zzs_jxse13ncpdk
ren zzs_jxse6 zzs_jxse6
ren zzs_jxszce zzs_jxszce
ren zzs_qcld zzs_qcld
ren zzs_ydkhj zzs_ydkhj
ren zzs_qmlddqse zzs_qmlddqse
ren zzs_sjdk zzs_sjdk
ren zzs_jyyns zzs_jyyns
ren zzs_mzyns zzs_mzyns
ren zzs_yns zzs_yns
ren zzs_yjcb zzs_yjcb
ren zzs_ncwj zzs_ncwj
ren zzs_ncyqwj zzs_ncyqwj
ren zzs_yn zzs_yn
ren zzs_bdyn zzs_bdyn
ren zzs_qj zzs_qj
ren zzs_yncb zzs_yncb
ren zzs_ydyn zzs_ydyn
ren zzs_nmwj zzs_nmwj
ren zzs_nmyqwj zzs_nmyqwj
ren zzs_cbdldse zzs_cbdldse
ren zzs_ldjxse zzs_ldjxse
ren zzs_hdse zzs_hdse
ren zzs_jzjt zzs_jzjt
ren zzckts_xse zzckts_xse
ren zzckts_msxse zzckts_msxse
ren zzckts_sbmsxse zzckts_sbmsxse
ren zzckts_mdtse zzckts_mdtse
ren zzckts_mdtsdje zzckts_mdtsdje
ren zzckts_tse zzckts_tse
ren zzckts_ytse zzckts_ytse
ren zzckts_mdse zzckts_mdse
ren zzckts_ncytwtse zzckts_ncytwtse
ren zzckts_sjtse zzckts_sjtse
ren zzckts_nmytwte zzckts_nmytwte
ren zzckts_stxfse zzckts_stxfse
ren zzckts_bsjke zzckts_bsjke
ren zzckts_bscke zzckts_bscke
ren zzckts_tqbscke zzckts_tqbscke
ren zzckts_zrhw zzckts_zrhw
ren zzckts_zchw zzckts_zchw
ren zzckts_nxhw zzckts_nxhw
ren zzckts_nxbslx zzckts_nxbslx
ren zzckts_gclj zzckts_gclj
ren zzckts_llgjf zzckts_llgjf
ren zzckts_hwjke zzckts_hwjke
ren zzckts_ynjkzzs zzckts_ynjkzzs
ren zzckts_ynjkxfs zzckts_ynjkxfs
ren zzckts_ynjkgs zzckts_ynjkgs
ren zzckts_ynckgs zzckts_ynckgs
ren xfs_xse xfs_xse
ren xfs_nxmzxse xfs_nxmzxse
ren xfs_ckmzxse xfs_ckmzxse
ren xfs_jzyj xfs_jzyj
ren xfs_dk xfs_dk
ren xfs_jz xfs_jz
ren xfs_yj xfs_yj
ren xfs_cjyj xfs_cjyj
ren xfs_yjdkdj xfs_yjdkdj
ren xfs_yjcb xfs_yjcb
ren xfs_ncwj xfs_ncwj
ren xfs_ncyqwj xfs_ncyqwj
ren xfs_yn xfs_yn
ren xfs_bdyn xfs_bdyn
ren xfs_yndkdj xfs_yndkdj
ren xfs_qj xfs_qj
ren xfs_yncb xfs_yncb
ren xfs_ydyn xfs_ydyn
ren xfs_nmwj xfs_nmwj
ren xfs_nmyqwj xfs_nmyqwj
ren yys_jzsr yys_jzsr
ren yys_bdjzsr yys_bdjzsr
ren yys_ydjzsr yys_ydjzsr
ren yys_kcyye yys_kcyye
ren yys_ysyye yys_ysyye
ren yys_msyye yys_msyye
ren yys_jm yys_jm
ren yys_yj yys_yj
ren yys_yjdkdj yys_yjdkdj
ren yys_yjcb yys_yjcb
ren yys_ncwj yys_ncwj
ren yys_yqwj yys_yqwj
ren yys_yn yys_yn
ren yys_bdyn yys_bdyn
ren yys_yndkdj yys_yndkdj
ren yys_qj yys_qj
ren yys_yncb yys_yncb
ren yys_ydyn yys_ydyn
ren yys_nmwj yys_nmwj
ren yys_nmyqwj yys_nmyqwj
ren fcs_mj fcs_mj
ren fcs_jsfcyzzy fcs_jsfcyzzy
ren fcs_zyjsyzhj fcs_zyjsyzhj
ren fcs_zysl fcs_zysl
ren fcs_zyjmse fcs_zyjmse
ren fcs_zyyjse fcs_zyyjse
ren fcs_zyynse fcs_zyynse
ren fcs_czzjsr fcs_czzjsr
ren fcs_czzfzjsr fcs_czzfzjsr
ren fcs_czjmse fcs_czjmse
ren fcs_czyjse fcs_czyjse
ren fcs_czynse fcs_czynse
ren cztdsys_mj cztdsys_mj
ren cztdsys_ysmj cztdsys_ysmj
ren cztdsys_jmse cztdsys_jmse
ren cztdsys_yjse cztdsys_yjse
ren cztdsys_ynse cztdsys_ynse
ren ccs_cycyjse ccs_cycyjse
ren ccs_sycyjse ccs_sycyjse
ren ccs_mtcyjse ccs_mtcyjse
ren ccs_qtclyjse ccs_qtclyjse
ren ccs_cbyjse ccs_cbyjse
ren ccs_jmse ccs_jmse
ren ccs_yjse ccs_yjse
ren ccs_ynse ccs_ynse
ren ccs_yndkdjse ccs_yndkdjse
ren tdzzs_zrmj tdzzs_zrmj
ren tdzzs_yjyjse tdzzs_yjyjse
ren tdzzs_ynyjse tdzzs_ynyjse
ren tdzzs_zrfdcsr tdzzs_zrfdcsr
ren tdzzs_zrptzfsr tdzzs_zrptzfsr
ren tdzzs_kchj tdzzs_kchj
ren tdzzs_ftdsyqje tdzzs_ftdsyqje
ren tdzzs_fkfcb tdzzs_fkfcb
ren tdzzs_fkffy tdzzs_fkffy
ren tdzzs_fzrfdcsj tdzzs_fzrfdcsj
ren tdzzs_fqtkc tdzzs_fqtkc
ren tdzzs_tdsyqje tdzzs_tdsyqje
ren tdzzs_jfpgj tdzzs_jfpgj
ren tdzzs_zrsj tdzzs_zrsj
ren tdzzs_zze tdzzs_zze
ren tdzzs_zzebkcje tdzzs_zzebkcje
ren tdzzs_jmse tdzzs_jmse
ren tdzzs_yjse tdzzs_yjse
ren tdzzs_ynse tdzzs_ynse
ren gds_ysmj gds_ysmj
ren gds_gdmj gds_gdmj
ren gds_qtmj gds_qtmj
ren gds_jmse gds_jmse
ren gds_yjse gds_yjse
ren gds_ynse gds_ynse
ren gds_cjjghj gds_cjjghj
ren gds_tdjyjg gds_tdjyjg
ren gds_fwjyjg gds_fwjyjg
ren gds_jmqsse gds_jmqsse
ren gds_yjqsse gds_yjqsse
ren gds_ynqsse gds_ynqsse
ren dfs_yjzys dfs_yjzys
ren dfs_yjcsjss dfs_yjcsjss
ren dfs_yjyys dfs_yjyys
ren dfs_ynzys dfs_ynzys
ren dfs_yncsjss dfs_yncsjss
ren dfs_yngrsds dfs_yngrsds
ren dfs_yndkdjgrsds dfs_yndkdjgrsds
ren dfs_yndkdjlxsds dfs_yndkdjlxsds
ren dfs_qyyngrsds dfs_qyyngrsds
ren dfs_ynyhs dfs_ynyhs
ren dfs_dkdjyhs dfs_dkdjyhs
ren dfs_ynyys dfs_ynyys
ren dfs_ynclgzs dfs_ynclgzs
ren dfs_yjxzsf dfs_yjxzsf
ren dfs_yjjyfj dfs_yjjyfj
ren dfs_yjwhjs dfs_yjwhjs
ren dfs_ynxzsf dfs_ynxzsf
ren dfs_ynjyfj dfs_ynjyfj
ren dfs_ynwhjs dfs_ynwhjs
ren dfs_ynshbx dfs_ynshbx
ren dfs_ynqt dfs_ynqt
ren dfs_ynfk dfs_ynfk
ren sds_yysr sds_yysr
ren sds_yycb sds_yycb
ren sds_yysjjfj sds_yysjjfj
ren sds_xsfy sds_xsfy
ren sds_glfy sds_glfy
ren sds_cwfy sds_cwfy
ren sds_zcjzss sds_zcjzss
ren sds_gyjzbdjsy sds_gyjzbdjsy
ren sds_tzsy sds_tzsy
ren sds_yylr sds_yylr
ren sds_yywsr sds_yywsr
ren sds_yywzc sds_yywzc
ren sds_lrze sds_lrze
ren sds_nstzzje sds_nstzzje
ren sds_nstzjse sds_nstzjse
ren sds_jwmbjn sds_jwmbjn
ren sds_nstzsd sds_nstzsd
ren sds_mbyqks sds_mbyqks
ren sds_ynssde sds_ynssde
ren sds_sl25 sds_sl25
ren sds_yjsdse sds_yjsdse
ren sds_jmsdse sds_jmsdse
ren sds_xwqy sds_xwqy
ren sds_gxqy sds_gxqy
ren sds_mzqydfs sds_mzqydfs
ren sds_gdqyh sds_gdqyh
ren sds_qt sds_qt
ren sds_dmsdse sds_dmsdse
ren sds_yjse sds_yjse
ren sds_jwyj sds_jwyj
ren sds_jwdm sds_jwdm
ren sds_sjyjsdse sds_sjyjsdse
ren sds_sjyjse sds_sjyjse
ren sds_ybse sds_ybse
ren sds_djdje sds_djdje
ren sds_wjrke sds_wjrke
ren sds_yqwje sds_yqwje
ren sds_jzjtse sds_jzjtse
ren sds_srsrze sds_srsrze
ren sds_srsl sds_srsl
ren sds_sryj sds_sryj
ren sds_cbcbze sds_cbcbze
ren sds_cbsl sds_cbsl
ren sds_cbyj sds_cbyj
ren sds_yjsl sds_yjsl
ren sds_yjyjse sds_yjyjse
ren sds_yjyjsdse sds_yjyjsdse
ren sds_yjybse sds_yjybse
ren sds_fzftyjse3 sds_fzftyjse3
ren sds_sjjnyjse3 sds_sjjnyjse3
ren sds_jdsjjne4 sds_jdsjjne4
ren lrb_yysr lrb_yysr
ren lrb_zysr lrb_zysr
ren lrb_qtsr lrb_qtsr
ren lrb_yycb lrb_yycb
ren lrb_zycb lrb_zycb
ren lrb_qtcb lrb_qtcb
ren lrb_yysjfj lrb_yysjfj
ren lrb_xsfy lrb_xsfy
ren lrb_glfy lrb_glfy
ren lrb_xcpfy lrb_xcpfy
ren lrb_zdfy lrb_zdfy
ren lrb_cwfy lrb_cwfy
ren lrb_zcjzss lrb_zcjzss
ren lrb_gyjzjsy lrb_gyjzjsy
ren lrb_tzsy lrb_tzsy
ren lrb_hytzsy lrb_hytzsy
ren lrb_yylr lrb_yylr
ren lrb_yywsr lrb_yywsr
ren lrb_btsr lrb_btsr
ren lrb_yywzc lrb_yywzc
ren lrb_gyjzzc lrb_gyjzzc
ren lrb_lrze lrb_lrze
ren lrb_sdsfy lrb_sdsfy
ren lrb_jlr lrb_jlr
ren lrb_kfplr lrb_kfplr
ren lrb_gdfplr lrb_gdfplr
ren lrb_wfplr lrb_wfplr
ren zcb_zcncs zcb_zcncs
ren zcb_cldzc zcb_cldzc
ren zcb_chbzj zcb_chbzj
ren zcb_cyszk zcb_cyszk
ren zcb_cch zcb_cch
ren zcb_cycl zcb_cycl
ren zcb_cfldzc zcb_cfldzc
ren zcb_cgdzc zcb_cgdzc
ren zcb_zcnms zcb_zcnms
ren zcb_mldzc zcb_mldzc
ren zcb_mhbzj zcb_mhbzj
ren zcb_myszk zcb_myszk
ren zcb_mch zcb_mch
ren zcb_mycl zcb_mycl
ren zcb_mfldzc zcb_mfldzc
ren zcb_mgdzc zcb_mgdzc
ren zcb_mgdzcyz zcb_mgdzcyz
ren zcb_mljzj zcb_mljzj
ren zcb_mgdzcjz zcb_mgdzcjz
ren zcb_fzncs zcb_fzncs
ren zcb_cldfz zcb_cldfz
ren zcb_cyfzk zcb_cyfzk
ren zcb_cfldfz zcb_cfldfz
ren zcb_ccqjk zcb_ccqjk
ren zcb_fznms zcb_fznms
ren zcb_mldfz zcb_mldfz
ren zcb_myfzk zcb_myfzk
ren zcb_mfldfz zcb_mfldfz
ren zcb_mcqjk zcb_mcqjk
ren zcb_qyncs zcb_qyncs
ren zcb_qynms zcb_qynms
ren zcb_sszbnms zcb_sszbnms
ren zcb_zbgjnms zcb_zbgjnms
ren xjb_xjlr xjb_xjlr
ren xjb_xsxj xjb_xsxj
ren xjb_sffh xjb_sffh
ren xjb_xjlc xjb_xjlc
ren xjb_gmsp xjb_gmsp
ren xjb_zfzg xjb_zfzg
gen zfqtsf = xjb_zfzzs + xjb_zfsds + xjb_zfqt 
replace zfqtsf = xjb_zfzzs + xjb_zfsds if xjb_zfqt == . 
replace zfqtsf = xjb_zfzzs + xjb_zfqt if xjb_zfsds == . 
replace zfqtsf = xjb_zfsds + xjb_zfqt if xjb_zfzzs == . 
replace zfqtsf = xjb_zfzzs if xjb_zfsds == . & xjb_zfqt == . 
replace zfqtsf = xjb_zfsds if xjb_zfzzs == . & xjb_zfqt == . 
replace zfqtsf = xjb_zfqt if xjb_zfzzs == . & xjb_zfsds == . 
replace zfqtsf = . if xjb_zfzzs == . & xjb_zfsds == . & xjb_zfqt == .
drop xjb_zfzzs
drop xjb_zfsds
drop xjb_zfqt
ren zfqtsf xjb_zfgzsf
ren xjb_jyxj xjb_jyxj
ren xjb_tzxj xjb_tzxj
ren xjb_czxj xjb_czxj
ren xjb_hlbd xjb_hlbd
ren xjb_xjzje xjb_xjzje
ren qt_wgsb qt_wgsb
ren qt_rzzlsb qt_rzzlsb
ren qt_wgbdc qt_wgbdc
ren qt_rzzlbdc qt_rzzlbdc
ren qt_zjgdzc qt_zjgdzc
ren qt_zjjygdzc qt_zjjygdzc
ren qt_zjjyfw qt_zjjyfw
ren qt_zjjksb qt_zjjksb
ren qt_nmjygdzcjz qt_nmjygdzcjz
ren qt_jyfwjz qt_jyfwjz
ren qt_jyjksbjz qt_jyjksbjz
ren qt_grsblw qt_grsblw
ren qt_jtzj qt_jtzj
ren qt_sbjtzj qt_sbjtzj
ren qt_fwjtzj qt_fwjtzj
ren qt_wghw qt_wghw
ren qt_wgryf qt_wgryf
ren qt_wgjgf qt_wgjgf
ren qt_wgxlf qt_wgxlf
ren qt_wgysf qt_wgysf
ren qt_wgyff qt_wgyff
ren qt_wgxxfw qt_wgxxfw
ren qt_wgwhcy qt_wgwhcy
ren qt_ggzc qt_ggzc
ren qt_sjfwzc qt_sjfwzc
ren qt_wlfwzc qt_wlfwzc
ren qt_wggkfw qt_wggkfw
ren qt_wgjcfw qt_wgjcfw
ren qt_wghwys qt_wghwys
ren qt_cc qt_cc
ren qt_wgyxdcfw qt_wgyxdcfw
ren qt_wgzxfw qt_wgzxfw
ren qt_wgjzlwzc qt_wgjzlwzc
ren qt_jzaz qt_jzaz
ren qt_xszs qt_xszs
ren qt_qtgczy qt_qtgczy
ren qt_wgzgpxf qt_wgzgpxf
ren qt_clzc qt_clzc
ren qt_qtzc qt_qtzc
ren qt_lxzzc qt_lxzzc
ren qt_jtgzjj qt_jtgzjj
ren qt_nczgs qt_nczgs
ren qt_nmzgs qt_nmzgs
ren qt_zcz qt_zcz
ren qt_zjz qt_zjz
ren qt_dlxfl 电力消费量
ren qt_mtxfl 煤炭消费量
ren qt_yxfl 油消费量
ren qt_sxfl qt_sxfl
save "E:/企业数据/税调数据(团队数据)/1 原始数据_税收调查数据2007-2016（统一变量名称）/税调`ii'新.dta" ,replace
}
