forvalues year = 2017(1)2020{
	* merge qyid
	foreach city in 七台河市 三亚市 三明市 三沙市 三门峡市 上海市 上饶市 东莞市 东营市 中卫市 中山市 临夏回族自治州 临汾市 临沂市 临沧市 丹东市 丽水市 丽江市 乌兰察布市 乌海市 乌鲁木齐市 乐山市 九江市 云浮市 亳州市 伊春市 伊犁哈萨克自治州 佛山市 佳木斯市 保定市 保山市 信阳市 儋州市 克孜勒苏柯尔克孜自治州 克拉玛依市 六安市 六盘水市 兰州市 兴安盟 内江市 凉山彝族自治州 包头市 北京市 北海市 十堰市 南京市 南充市 南宁市 南平市 南昌市 南通市 南阳市 博尔塔拉蒙古自治州 厦门市 双鸭山市 台州市 合肥市 吉安市 吉林市 吐鲁番市 吕梁市 吴忠市 周口市 呼伦贝尔市 呼和浩特市 和田地区 咸宁市 咸阳市 哈密市 哈尔滨市 唐山市 商丘市 商洛市 喀什地区 嘉兴市 嘉峪关市 四平市 固原市 塔城地区 大兴安岭地区 大同市 大庆市 大理白族自治州 大连市 天水市 天津市 太原市 威海市 娄底市 孝感市 宁德市 宁波市 安庆市 安康市 安阳市 安顺市 定西市 宜宾市 宜昌市 宜春市 宝鸡市 宣城市 宿州市 宿迁市 山南市 岳阳市 崇左市 巴中市 巴彦淖尔市 巴音郭楞蒙古自治州 常州市 常德市 平凉市 平顶山市 广元市 广安市 广州市 庆阳市 廊坊市 延安市 延边朝鲜族自治州 开封市 张家口市 张家界市 张掖市 徐州市 德宏傣族景颇族自治州 德州市 德阳市 忻州市 怀化市 怒江傈僳族自治州 恩施土家族苗族自治州 惠州市 成都市 扬州市 承德市 抚州市 抚顺市 拉萨市 揭阳市 攀枝花市 文山壮族苗族自治州 新乡市 新余市 无锡市 日喀则市 日照市 昆明市 昌吉回族自治州 昌都市 昭通市 晋中市 晋城市 普洱市 景德镇市 曲靖市 朔州市 朝阳市 本溪市 来宾市 杭州市 松原市 林芝市 果洛藏族自治州 枣庄市 柳州市 株洲市 桂林市 梅州市 梧州市 楚雄彝族自治州 榆林市 武威市 武汉市 毕节市 永州市 汉中市 汕头市 汕尾市 江门市 池州市 沈阳市 沧州市 河池市 河源市 泉州市 泰安市 泰州市 泸州市 洛阳市 济南市 济宁市 海东市 海北藏族自治州 海南藏族自治州 海口市 海西蒙古族藏族自治州 淄博市 淮北市 淮南市 淮安市 深圳市 清远市 温州市 渭南市 湖州市 湘潭市 湘西土家族苗族自治州 湛江市 滁州市 滨州市 漯河市 漳州市 潍坊市 潮州市 濮阳市 烟台市 焦作市 牡丹江市 玉林市 玉树藏族自治州 玉溪市 珠海市 甘南藏族自治州 甘孜藏族自治州 白城市 白山市 白银市 百色市 益阳市 盐城市 盘锦市 眉山市 石嘴山市 石家庄市 福州市 秦皇岛市 红河哈尼族彝族自治州 绍兴市 绥化市 绵阳市 聊城市 肇庆市 自贡市 舟山市 芜湖市 苏州市 茂名市 荆州市 荆门市 莆田市 菏泽市 萍乡市 营口市 葫芦岛市 蚌埠市 衡水市 衡阳市 衢州市 襄阳市 西双版纳傣族自治州 西宁市 西安市 许昌市 贵港市 贵阳市 贺州市 资阳市 赣州市 赤峰市 辽源市 辽阳市 达州市 运城市 连云港市 迪庆藏族自治州 通化市 通辽市 遂宁市 遵义市 邢台市 那曲市 邯郸市 邵阳市 郑州市 郴州市 鄂尔多斯市 鄂州市 酒泉市 重庆市 重庆市郊县 金华市 金昌市 钦州市 铁岭市 铜仁市 铜川市 铜陵市 银川市 锡林郭勒盟 锦州市 镇江市 长春市 长沙市 长治市 阜新市 阜阳市 防城港市 阳江市 阳泉市 阿克苏地区 阿勒泰地区 阿坝藏族羌族自治州 阿拉善盟 阿里地区 陇南市 随州市 雅安市 青岛市 鞍山市 韶关市 马鞍山市 驻马店市 鸡西市 鹤壁市 鹤岗市 鹰潭市 黄冈市 黄南藏族自治州 黄山市 黄石市 黑河市 黔东南苗族侗族自治州 黔南布依族苗族自治州 黔西南布依族苗族自治州 齐齐哈尔市 龙岩市 {
		use "E:/企业数据/税调数据(团队数据)/3 税调_dta（生成qyid）/税调`year'新.dta",clear
		merge 1:m qyid using "E:/企业数据/税调数据(团队数据)/3 工商_dta（生成qyid）/`city'-基本信息.dta"
		keep if _merge == 3
		drop _merge
		* duplicates drop qyid,force
		save "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调-`city'.dta",replace
	}
	use "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调-七台河市.dta",clear
	foreach city in 三亚市 三明市 三沙市 三门峡市 上海市 上饶市 东莞市 东营市 中卫市 中山市 临夏回族自治州 临汾市 临沂市 临沧市 丹东市 丽水市 丽江市 乌兰察布市 乌海市 乌鲁木齐市 乐山市 九江市 云浮市 亳州市 伊春市 伊犁哈萨克自治州 佛山市 佳木斯市 保定市 保山市 信阳市 儋州市 克孜勒苏柯尔克孜自治州 克拉玛依市 六安市 六盘水市 兰州市 兴安盟 内江市 凉山彝族自治州 包头市 北京市 北海市 十堰市 南京市 南充市 南宁市 南平市 南昌市 南通市 南阳市 博尔塔拉蒙古自治州 厦门市 双鸭山市 台州市 合肥市 吉安市 吉林市 吐鲁番市 吕梁市 吴忠市 周口市 呼伦贝尔市 呼和浩特市 和田地区 咸宁市 咸阳市 哈密市 哈尔滨市 唐山市 商丘市 商洛市 喀什地区 嘉兴市 嘉峪关市 四平市 固原市 塔城地区 大兴安岭地区 大同市 大庆市 大理白族自治州 大连市 天水市 天津市 太原市 威海市 娄底市 孝感市 宁德市 宁波市 安庆市 安康市 安阳市 安顺市 定西市 宜宾市 宜昌市 宜春市 宝鸡市 宣城市 宿州市 宿迁市 山南市 岳阳市 崇左市 巴中市 巴彦淖尔市 巴音郭楞蒙古自治州 常州市 常德市 平凉市 平顶山市 广元市 广安市 广州市 庆阳市 廊坊市 延安市 延边朝鲜族自治州 开封市 张家口市 张家界市 张掖市 徐州市 德宏傣族景颇族自治州 德州市 德阳市 忻州市 怀化市 怒江傈僳族自治州 恩施土家族苗族自治州 惠州市 成都市 扬州市 承德市 抚州市 抚顺市 拉萨市 揭阳市 攀枝花市 文山壮族苗族自治州 新乡市 新余市 无锡市 日喀则市 日照市 昆明市 昌吉回族自治州 昌都市 昭通市 晋中市 晋城市 普洱市 景德镇市 曲靖市 朔州市 朝阳市 本溪市 来宾市 杭州市 松原市 林芝市 果洛藏族自治州 枣庄市 柳州市 株洲市 桂林市 梅州市 梧州市 楚雄彝族自治州 榆林市 武威市 武汉市 毕节市 永州市 汉中市 汕头市 汕尾市 江门市 池州市 沈阳市 沧州市 河池市 河源市 泉州市 泰安市 泰州市 泸州市 洛阳市 济南市 济宁市 海东市 海北藏族自治州 海南藏族自治州 海口市 海西蒙古族藏族自治州 淄博市 淮北市 淮南市 淮安市 深圳市 清远市 温州市 渭南市 湖州市 湘潭市 湘西土家族苗族自治州 湛江市 滁州市 滨州市 漯河市 漳州市 潍坊市 潮州市 濮阳市 烟台市 焦作市 牡丹江市 玉林市 玉树藏族自治州 玉溪市 珠海市 甘南藏族自治州 甘孜藏族自治州 白城市 白山市 白银市 百色市 益阳市 盐城市 盘锦市 眉山市 石嘴山市 石家庄市 福州市 秦皇岛市 红河哈尼族彝族自治州 绍兴市 绥化市 绵阳市 聊城市 肇庆市 自贡市 舟山市 芜湖市 苏州市 茂名市 荆州市 荆门市 莆田市 菏泽市 萍乡市 营口市 葫芦岛市 蚌埠市 衡水市 衡阳市 衢州市 襄阳市 西双版纳傣族自治州 西宁市 西安市 许昌市 贵港市 贵阳市 贺州市 资阳市 赣州市 赤峰市 辽源市 辽阳市 达州市 运城市 连云港市 迪庆藏族自治州 通化市 通辽市 遂宁市 遵义市 邢台市 那曲市 邯郸市 邵阳市 郑州市 郴州市 鄂尔多斯市 鄂州市 酒泉市 重庆市 重庆市郊县 金华市 金昌市 钦州市 铁岭市 铜仁市 铜川市 铜陵市 银川市 锡林郭勒盟 锦州市 镇江市 长春市 长沙市 长治市 阜新市 阜阳市 防城港市 阳江市 阳泉市 阿克苏地区 阿勒泰地区 阿坝藏族羌族自治州 阿拉善盟 阿里地区 陇南市 随州市 雅安市 青岛市 鞍山市 韶关市 马鞍山市 驻马店市 鸡西市 鹤壁市 鹤岗市 鹰潭市 黄冈市 黄南藏族自治州 黄山市 黄石市 黑河市 黔东南苗族侗族自治州 黔南布依族苗族自治州 黔西南布依族苗族自治州 齐齐哈尔市 龙岩市 {
		append using "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调-`city'.dta"
	}
	save "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调`year'(匹配后-qyid).dta",replace
}

forvalues year = 2017(1)2020{
	* merge qymc
	use "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调`year'(匹配后-qyid).dta",clear
	append using "E:/企业数据/税调数据(团队数据)/3 税调_dta（生成qyid）/税调`year'新.dta"
	sort qyid 统一社会信用代码
	bysort qyid:gen p = 1 if qyid == qyid[_n+1] & 统一社会信用代码 == ""
	replace p = 0 if p == .
	keep if 统一社会信用代码 == "" & p == 0
	drop p
	* qymc处理和替换
	replace qymc = subinstr(qymc, "*", "", .)
	replace qymc = subinstr(qymc, `"""', "", .)
	replace qymc = subinstr(qymc, `"-"', "", .)
	replace qymc = subinstr(qymc, `"."', "", .)
	replace qymc = subinstr(qymc, `"/"', "", .)
	replace qymc = subinstr(qymc, `"7广州"', "广州", .)
	replace qymc = subinstr(qymc, `"？"', "", .)
	replace qymc = subinstr(qymc, `"("', "（", .)
	replace qymc = subinstr(qymc, `")"', "）", .)
	replace qymc = subinstr(qymc, `"Ｔ"', "T", .)
	replace qymc = subinstr(qymc, `"Ｋ"', "K", .)
	replace qymc = subinstr(qymc, `"Ｕ"', "U", .)
	replace qymc = subinstr(qymc, `"Ｌ"', "L", .)
	replace qymc = subinstr(qymc, `"Ｄ"', "D", .)
	replace qymc = subinstr(qymc, `"Ｇ"', "G", .)
	replace qymc = subinstr(qymc, `"Ｃ"', "C", .)
	replace qymc = subinstr(qymc, `"Ｓ"', "S", .)
	replace qymc = subinstr(qymc, `"Ｘ"', "X", .)
	replace qymc = subinstr(qymc, `"Ｍ"', "M", .)
	replace qymc = subinstr(qymc, `"Ｅ"', "E", .)
	replace qymc = subinstr(qymc, `"Ｉ"', "I", .)
	replace qymc = subinstr(qymc, `"Ｐ"', "P", .)
	replace qymc = subinstr(qymc, `"Ｆ"', "F", .)
	replace qymc = subinstr(qymc, `"Ｒ"', "R", .)
	replace qymc = subinstr(qymc, `"Ｏ"', "O", .)
	replace qymc = subinstr(qymc, `"Ｎ"', "N", .)
	replace qymc = subinstr(qymc, `"Ａ"', "A", .)
	replace qymc = subinstr(qymc, `"Ｏ"', "O", .)
	replace qymc = subinstr(qymc, `"Ｈ"', "H", .)
	replace qymc = subinstr(qymc, `"０"', "0", .)
	replace qymc = subinstr(qymc, `"６"', "6", .)
	replace qymc = subinstr(qymc, `"５"', "5", .)
	replace qymc = subinstr(qymc, `"（山东奥伦庄园葡萄酒有"', "", .)
	replace qymc = subinstr(qymc, `"（浠水顺达矿业有"', "", .)
	replace qymc = subinstr(qymc, `"（乐百氏饮用水有"', "", .)
	replace qymc = subinstr(qymc, `"（江阴市澄业化工有限公司、江阴澄业化工有"', "", .)
	replace qymc = subinstr(qymc, `"（原博山北方铸造有"', "", .)
	replace qymc = subinstr(qymc, `"（宁波肇成天然沐浴用品有"', "", .)
	replace qymc = subinstr(qymc, `"（象山科德建材安装有"', "", .)
	replace qymc = subinstr(qymc, `"（象山科德建材安装有"', "", .)
	replace qymc = subinstr(qymc, `"（慈溪市建利达合纤有"', "", .)
	replace qymc = subinstr(qymc, `"有"', "有限公司", .) if substr(qymc, -3, 3) == "有"
	replace qymc = subinstr(qymc, `"（泰兴市永辉车灯塑件有限"', "", .)
	replace qymc = subinstr(qymc, `"（泰兴市环星服装辅料有限"', "", .)
	replace qymc = subinstr(qymc, `"（慈溪市佳诚机械有限"', "", .)
	replace qymc = subinstr(qymc, `"（浙江海通食品集团股份有限"', "", .)
	replace qymc = subinstr(qymc, `"（慈溪市杰克工具有限"', "", .)
	replace qymc = subinstr(qymc, `"（无锡市科伦达仓储物流设备有限"', "", .)
	replace qymc = subinstr(qymc, `"（慈溪市福达轴承有限"', "", .)
	replace qymc = subinstr(qymc, `"（吉林市恒新机械制造有限"', "", .)
	replace qymc = subinstr(qymc, `"有限"', "有限公司", .) if substr(qymc, -6, 6) == "有限"
	replace qymc = subinstr(qymc, `"（桂林桂广滑石开发有限公"', "", .)
	replace qymc = subinstr(qymc, `"（平原喜盈门毛巾有限公"', "", .)
	replace qymc = subinstr(qymc, `"（慈溪市百盛塑胶实业有限公"', "", .)
	replace qymc = subinstr(qymc, `"（浙江中兴电子有限公"', "", .)
	replace qymc = subinstr(qymc, `"（宁波东方琴业有限公"', "", .)
	replace qymc = subinstr(qymc, `"（慈溪斯佳电器有限公"', "", .)
	replace qymc = subinstr(qymc, `"（宁波飞翔阀门有限公"', "", .)
	replace qymc = subinstr(qymc, `"（张家港市奔达精密锻造有限公"', "", .)
	replace qymc = subinstr(qymc, `"有限公"', "有限公司", .) if substr(qymc, -9, 9) == "有限公"
	gen temp = ustrregexs(0) if ustrregexm(qymc, "（(.*)$") & index(qymc, "（") & !index(qymc, "）")
	replace qymc = subinstr(qymc, temp, "", .)
	drop temp
	replace qymc = subinstr(qymc, `"\{"', "（", .)
	replace qymc = subinstr(qymc, `"\}"', "）", .)
	* 只有一半括号的就不再处理了，因为匹配的时候会把所有的括号删除进行匹配

	replace qymc = subinstr(qymc, `"有公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"smc"', "SMC", .)
	replace qymc = subinstr(qymc, "\`", "", .)
	replace qymc = subinstr(qymc, `"f昌"', "昌", .)
	replace qymc = subinstr(qymc, `"tcc"', "TCC", .)
	replace qymc = subinstr(qymc, `"u广"', "广", .)
	replace qymc = subinstr(qymc, `"·"', "", .)
	replace qymc = subinstr(qymc, `"（有限公司）"', "有限公司", .)

	replace qymc = subinstr(qymc, `"""', "", .)
	replace qymc = subinstr(qymc, `"*"', "", .)
	replace qymc = subinstr(qymc, `"."', "", .)
	replace qymc = subinstr(qymc, `"/"', "", .)
	replace qymc = subinstr(qymc, `"▲"', "", .)
	replace qymc = subinstr(qymc, `"△"', "", .)
	replace qymc = subinstr(qymc, `"◆"', "", .)
	replace qymc = subinstr(qymc, `"◇"', "", .)
	replace qymc = subinstr(qymc, `"曹丿"', "", .)
	replace qymc = subinstr(qymc, `"○"', "", .)
	replace qymc = subinstr(qymc, `"☆"', "", .)
	replace qymc = subinstr(qymc, `"AA"', "", .)
	replace qymc = subinstr(qymc, `"aa"', "", .)
	replace qymc = subinstr(qymc, `"１"', "1", .)
	replace qymc = subinstr(qymc, `"５"', "5", .)
	replace qymc = subinstr(qymc, `"６"', "6", .)
	replace qymc = subinstr(qymc, `"０"', "0", .)
	replace qymc = subinstr(qymc, `"Ｍ"', "M", .)
	replace qymc = subinstr(qymc, `"３"', "3", .)
	replace qymc = subinstr(qymc, `"Ｔ"', "T", .)
	replace qymc = subinstr(qymc, `"Ｐ"', "P", .)
	replace qymc = subinstr(qymc, `"Ｓ"', "S", .)
	replace qymc = subinstr(qymc, `"Ｌ"', "L", .)
	replace qymc = subinstr(qymc, `"Ｃ"', "C", .)
	replace qymc = subinstr(qymc, `"Ｋ"', "K", .)
	replace qymc = subinstr(qymc, `"Ｕ"', "U", .)
	replace qymc = subinstr(qymc, `"Ｈ"', "H", .)
	replace qymc = subinstr(qymc, `"Ｘ"', "X", .)
	replace qymc = subinstr(qymc, `" "', "", .)
	replace qymc = subinstr(qymc, `"？"', "", .)
	replace qymc = subinstr(qymc, `"Ｆ"', "F", .)
	replace qymc = subinstr(qymc, `"Ｒ"', "R", .)
	replace qymc = subinstr(qymc, `"Ｏ"', "O", .)
	replace qymc = subinstr(qymc, `"Ｎ"', "N", .)
	replace qymc = subinstr(qymc, `"Ａ"', "A", .)
	replace qymc = subinstr(qymc, `"C"', "C", .)
	replace qymc = subinstr(qymc, `"Ｄ"', "D", .)
	replace qymc = subinstr(qymc, `"Ｇ"', "G", .)
	replace qymc = subinstr(qymc, `"Ｅ"', "E", .)
	replace qymc = subinstr(qymc, `"Ｉ"', "I", .)
	replace qymc = subinstr(qymc, `"("', "（", .)
	replace qymc = subinstr(qymc, `")"', "）", .)
	replace qymc = subinstr(qymc, `"有"', "有限公司", .) if substr(qymc, -3, 3) == "有"
	replace qymc = subinstr(qymc, `"有限"', "有限公司", .) if substr(qymc, -6, 6) == "有限"
	replace qymc = subinstr(qymc, `"有限公"', "有限公司", .) if substr(qymc, -9, 9) == "有限公"
	replace qymc = subinstr(qymc, `"有公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有责任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有责公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限有司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公司有司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责任司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责任"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责任公"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有责任限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有线责任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"人限责任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"责任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限现任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限表任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限则任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限責任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公司现任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限制任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限?任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限信任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公司任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限作任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限质任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责作任公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限有限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公司责任司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公责任司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责仁公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责人公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责认公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责令公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责有限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限责"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公司有限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有泥公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有现公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有责限有限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限宝鸡"', "有限公司宝鸡", .)
	replace qymc = subinstr(qymc, `"有械公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有线公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有了公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有敢公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有好公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有妈公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有阴公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有利公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有县公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有些公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有效公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有恨公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有险公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有新公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有发公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有眼公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有取公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有艰公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有向公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有良公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有业公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有服公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有奶公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有很公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有先公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有项公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有份公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限人公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限价公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有了限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限尺公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限化公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限期公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有想限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限厂公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限业公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限）公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限个公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有好限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"（有限）公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有先限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限）公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限=公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限年公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限发公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有1限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有实业公司"', "实业公司", .)
	replace qymc = subinstr(qymc, `"有限期公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限业公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有取胜公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"时有限装公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限翁公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有）限公司"', "）有限公司", .)
	replace qymc = subinstr(qymc, `"有限那公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有开发公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限衣公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有发限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有好受公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有箱限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限食品"', "食品有限", .)
	replace qymc = subinstr(qymc, `"有限面粉"', "面粉有限", .)
	replace qymc = subinstr(qymc, `"有限股份公司"', "股份有限公司", .)
	replace qymc = subinstr(qymc, `"有限工作"', "有限", .)
	replace qymc = subinstr(qymc, `"有限材料公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限花炮公司"', "花炮有限公司", .)
	replace qymc = subinstr(qymc, `"有限任责公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限发展公司"', "发展有限公司", .)
	replace qymc = subinstr(qymc, `"有限销售公司"', "销售有限公司", .)
	replace qymc = subinstr(qymc, `"有限集团公司"', "集团有限公司", .)
	replace qymc = subinstr(qymc, `"有限实业公司"', "实业有限公司", .)
	replace qymc = subinstr(qymc, `"有限合作公司"', "合作有限公司", .)
	replace qymc = subinstr(qymc, `"有限工限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限制品公司"', "制品有限公司", .)
	replace qymc = subinstr(qymc, `"有限开发公司"', "开发有限公司", .)
	replace qymc = subinstr(qymc, `"有限制造公司"', "制造有限公司", .)
	replace qymc = subinstr(qymc, `"有限服饰公司"', "服饰有限公司", .)
	replace qymc = subinstr(qymc, `"有限金属公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限工业公司"', "工业有限公司", .)
	replace qymc = subinstr(qymc, `"有限工程公司"', "工程有限公司", .)
	replace qymc = subinstr(qymc, `"有限公限公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限两用公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限电力公司"', "电力有限公司", .)
	replace qymc = subinstr(qymc, `"有限工是司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公工司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公是司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限钢丝"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限工司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限分司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"股份有限合作"', "股份有限公司", .)
	replace qymc = subinstr(qymc, `"有限公同"', "有限公司", .)
	replace qymc = subinstr(qymc, `"股份有限第六生"', "股份有限公司第六生", .)
	replace qymc = subinstr(qymc, `"有限化司垫江县化化司"', "有限公司垫江县分公司", .)
	replace qymc = subinstr(qymc, `"有限制品责任"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限工时"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限现任责公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限共司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限攻司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限工公"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公饲"', "有限公司", .)
	replace qymc = subinstr(qymc, `"（福颜化工有限公）"', "（福颜化工有限公司）", .)
	replace qymc = subinstr(qymc, `"有限（责任）公司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限化司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公试"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限毛织加工"', "毛织加工有限", .)
	replace qymc = subinstr(qymc, `"胶有限以司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限制品"', "有限公司", .)
	replace qymc = subinstr(qymc, `"（有限外）"', "", .)
	replace qymc = subinstr(qymc, `"有限根数"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限劳动服务公司"', "劳动服务有限公司", .)
	replace qymc = subinstr(qymc, `"有限公事"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限云司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公避"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公番禺厂"', "有限公司番禺厂", .)
	replace qymc = subinstr(qymc, `"有限会司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限恭送"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公）"', "有限公司）", .)
	replace qymc = subinstr(qymc, `"有限公怀"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公厂"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限工资"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公式"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限工商"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公词"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限以司"', "有限公司", .)
	replace qymc = subinstr(qymc, `"有限公限"', "有限公司", .)
	drop if qymc == ""
	save "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调`year'(待匹配-名称).dta",replace
	foreach city in 七台河市 三亚市 三明市 三沙市 三门峡市 上海市 上饶市 东莞市 东营市 中卫市 中山市 临夏回族自治州 临汾市 临沂市 临沧市 丹东市 丽水市 丽江市 乌兰察布市 乌海市 乌鲁木齐市 乐山市 九江市 云浮市 亳州市 伊春市 伊犁哈萨克自治州 佛山市 佳木斯市 保定市 保山市 信阳市 儋州市 克孜勒苏柯尔克孜自治州 克拉玛依市 六安市 六盘水市 兰州市 兴安盟 内江市 凉山彝族自治州 包头市 北京市 北海市 十堰市 南京市 南充市 南宁市 南平市 南昌市 南通市 南阳市 博尔塔拉蒙古自治州 厦门市 双鸭山市 台州市 合肥市 吉安市 吉林市 吐鲁番市 吕梁市 吴忠市 周口市 呼伦贝尔市 呼和浩特市 和田地区 咸宁市 咸阳市 哈密市 哈尔滨市 唐山市 商丘市 商洛市 喀什地区 嘉兴市 嘉峪关市 四平市 固原市 塔城地区 大兴安岭地区 大同市 大庆市 大理白族自治州 大连市 天水市 天津市 太原市 威海市 娄底市 孝感市 宁德市 宁波市 安庆市 安康市 安阳市 安顺市 定西市 宜宾市 宜昌市 宜春市 宝鸡市 宣城市 宿州市 宿迁市 山南市 岳阳市 崇左市 巴中市 巴彦淖尔市 巴音郭楞蒙古自治州 常州市 常德市 平凉市 平顶山市 广元市 广安市 广州市 庆阳市 廊坊市 延安市 延边朝鲜族自治州 开封市 张家口市 张家界市 张掖市 徐州市 德宏傣族景颇族自治州 德州市 德阳市 忻州市 怀化市 怒江傈僳族自治州 恩施土家族苗族自治州 惠州市 成都市 扬州市 承德市 抚州市 抚顺市 拉萨市 揭阳市 攀枝花市 文山壮族苗族自治州 新乡市 新余市 无锡市 日喀则市 日照市 昆明市 昌吉回族自治州 昌都市 昭通市 晋中市 晋城市 普洱市 景德镇市 曲靖市 朔州市 朝阳市 本溪市 来宾市 杭州市 松原市 林芝市 果洛藏族自治州 枣庄市 柳州市 株洲市 桂林市 梅州市 梧州市 楚雄彝族自治州 榆林市 武威市 武汉市 毕节市 永州市 汉中市 汕头市 汕尾市 江门市 池州市 沈阳市 沧州市 河池市 河源市 泉州市 泰安市 泰州市 泸州市 洛阳市 济南市 济宁市 海东市 海北藏族自治州 海南藏族自治州 海口市 海西蒙古族藏族自治州 淄博市 淮北市 淮南市 淮安市 深圳市 清远市 温州市 渭南市 湖州市 湘潭市 湘西土家族苗族自治州 湛江市 滁州市 滨州市 漯河市 漳州市 潍坊市 潮州市 濮阳市 烟台市 焦作市 牡丹江市 玉林市 玉树藏族自治州 玉溪市 珠海市 甘南藏族自治州 甘孜藏族自治州 白城市 白山市 白银市 百色市 益阳市 盐城市 盘锦市 眉山市 石嘴山市 石家庄市 福州市 秦皇岛市 红河哈尼族彝族自治州 绍兴市 绥化市 绵阳市 聊城市 肇庆市 自贡市 舟山市 芜湖市 苏州市 茂名市 荆州市 荆门市 莆田市 菏泽市 萍乡市 营口市 葫芦岛市 蚌埠市 衡水市 衡阳市 衢州市 襄阳市 西双版纳傣族自治州 西宁市 西安市 许昌市 贵港市 贵阳市 贺州市 资阳市 赣州市 赤峰市 辽源市 辽阳市 达州市 运城市 连云港市 迪庆藏族自治州 通化市 通辽市 遂宁市 遵义市 邢台市 那曲市 邯郸市 邵阳市 郑州市 郴州市 鄂尔多斯市 鄂州市 酒泉市 重庆市 重庆市郊县 金华市 金昌市 钦州市 铁岭市 铜仁市 铜川市 铜陵市 银川市 锡林郭勒盟 锦州市 镇江市 长春市 长沙市 长治市 阜新市 阜阳市 防城港市 阳江市 阳泉市 阿克苏地区 阿勒泰地区 阿坝藏族羌族自治州 阿拉善盟 阿里地区 陇南市 随州市 雅安市 青岛市 鞍山市 韶关市 马鞍山市 驻马店市 鸡西市 鹤壁市 鹤岗市 鹰潭市 黄冈市 黄南藏族自治州 黄山市 黄石市 黑河市 黔东南苗族侗族自治州 黔南布依族苗族自治州 黔西南布依族苗族自治州 齐齐哈尔市 龙岩市 {
	use "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调`year'(待匹配-名称).dta",clear
	drop 统一社会信用代码
	merge m:m qymc using "E:/企业数据/税调数据(团队数据)/3 工商_dta（生成qyid）/`city'-基本信息.dta"
	keep if _merge == 3
	drop _merge
	*duplicates drop qyid,force
	save "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调-`city'(qymc).dta",replace
	}
	use "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调-七台河市(qymc).dta",clear
	foreach city in 三亚市 三明市 三沙市 三门峡市 上海市 上饶市 东莞市 东营市 中卫市 中山市 临夏回族自治州 临汾市 临沂市 临沧市 丹东市 丽水市 丽江市 乌兰察布市 乌海市 乌鲁木齐市 乐山市 九江市 云浮市 亳州市 伊春市 伊犁哈萨克自治州 佛山市 佳木斯市 保定市 保山市 信阳市 儋州市 克孜勒苏柯尔克孜自治州 克拉玛依市 六安市 六盘水市 兰州市 兴安盟 内江市 凉山彝族自治州 包头市 北京市 北海市 十堰市 南京市 南充市 南宁市 南平市 南昌市 南通市 南阳市 博尔塔拉蒙古自治州 厦门市 双鸭山市 台州市 合肥市 吉安市 吉林市 吐鲁番市 吕梁市 吴忠市 周口市 呼伦贝尔市 呼和浩特市 和田地区 咸宁市 咸阳市 哈密市 哈尔滨市 唐山市 商丘市 商洛市 喀什地区 嘉兴市 嘉峪关市 四平市 固原市 塔城地区 大兴安岭地区 大同市 大庆市 大理白族自治州 大连市 天水市 天津市 太原市 威海市 娄底市 孝感市 宁德市 宁波市 安庆市 安康市 安阳市 安顺市 定西市 宜宾市 宜昌市 宜春市 宝鸡市 宣城市 宿州市 宿迁市 山南市 岳阳市 崇左市 巴中市 巴彦淖尔市 巴音郭楞蒙古自治州 常州市 常德市 平凉市 平顶山市 广元市 广安市 广州市 庆阳市 廊坊市 延安市 延边朝鲜族自治州 开封市 张家口市 张家界市 张掖市 徐州市 德宏傣族景颇族自治州 德州市 德阳市 忻州市 怀化市 怒江傈僳族自治州 恩施土家族苗族自治州 惠州市 成都市 扬州市 承德市 抚州市 抚顺市 拉萨市 揭阳市 攀枝花市 文山壮族苗族自治州 新乡市 新余市 无锡市 日喀则市 日照市 昆明市 昌吉回族自治州 昌都市 昭通市 晋中市 晋城市 普洱市 景德镇市 曲靖市 朔州市 朝阳市 本溪市 来宾市 杭州市 松原市 林芝市 果洛藏族自治州 枣庄市 柳州市 株洲市 桂林市 梅州市 梧州市 楚雄彝族自治州 榆林市 武威市 武汉市 毕节市 永州市 汉中市 汕头市 汕尾市 江门市 池州市 沈阳市 沧州市 河池市 河源市 泉州市 泰安市 泰州市 泸州市 洛阳市 济南市 济宁市 海东市 海北藏族自治州 海南藏族自治州 海口市 海西蒙古族藏族自治州 淄博市 淮北市 淮南市 淮安市 深圳市 清远市 温州市 渭南市 湖州市 湘潭市 湘西土家族苗族自治州 湛江市 滁州市 滨州市 漯河市 漳州市 潍坊市 潮州市 濮阳市 烟台市 焦作市 牡丹江市 玉林市 玉树藏族自治州 玉溪市 珠海市 甘南藏族自治州 甘孜藏族自治州 白城市 白山市 白银市 百色市 益阳市 盐城市 盘锦市 眉山市 石嘴山市 石家庄市 福州市 秦皇岛市 红河哈尼族彝族自治州 绍兴市 绥化市 绵阳市 聊城市 肇庆市 自贡市 舟山市 芜湖市 苏州市 茂名市 荆州市 荆门市 莆田市 菏泽市 萍乡市 营口市 葫芦岛市 蚌埠市 衡水市 衡阳市 衢州市 襄阳市 西双版纳傣族自治州 西宁市 西安市 许昌市 贵港市 贵阳市 贺州市 资阳市 赣州市 赤峰市 辽源市 辽阳市 达州市 运城市 连云港市 迪庆藏族自治州 通化市 通辽市 遂宁市 遵义市 邢台市 那曲市 邯郸市 邵阳市 郑州市 郴州市 鄂尔多斯市 鄂州市 酒泉市 重庆市 重庆市郊县 金华市 金昌市 钦州市 铁岭市 铜仁市 铜川市 铜陵市 银川市 锡林郭勒盟 锦州市 镇江市 长春市 长沙市 长治市 阜新市 阜阳市 防城港市 阳江市 阳泉市 阿克苏地区 阿勒泰地区 阿坝藏族羌族自治州 阿拉善盟 阿里地区 陇南市 随州市 雅安市 青岛市 鞍山市 韶关市 马鞍山市 驻马店市 鸡西市 鹤壁市 鹤岗市 鹰潭市 黄冈市 黄南藏族自治州 黄山市 黄石市 黑河市 黔东南苗族侗族自治州 黔南布依族苗族自治州 黔西南布依族苗族自治州 齐齐哈尔市 龙岩市 {
		append using "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调-`city'(qymc).dta"
	}
	save "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调`year'(匹配后-名称).dta",replace
	* merge qyid + qymc
	use "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调`year'(匹配后-qyid).dta",clear
	append using "E:/企业数据/税调数据(团队数据)/3 税调-工商/税调`year'(匹配后-名称).dta"
	duplicates drop qyid,force
	duplicates drop 统一社会信用代码,force
	save "E:/企业数据/税调数据(团队数据)/3 税调-工商匹配结果/税调`year'(qyid+qymc).dta",replace
}