# -*- coding: utf-8 -*-
"""
Created on Tue May  9 15:34:13 2023

@author: ljh93
"""
import pandas as pd
import os
def normalize(st):
    st = str(st)
    st0 = st.replace(" ","")
    st0 = st0.replace("（","(")
    st0 = st0.replace("）",")")
    st0 = str.lower(st0)
    return st0
# 导出路径
road0 = "E:/"
infos = pd.DataFrame()
# 工商注册数据地址
road = r"E:\企业数据\工商数据_统一社会信用代码"
# 逐省进行匹配
citys = os.listdir(road)
citys = ['七台河市.csv',
 '三亚市.csv',
 '三明市.csv',
 '三沙市.csv',
 '三门峡市.csv',
 '上海市.csv',
 '上饶市.csv',
 '东莞市.csv',
 '东营市.csv',
 '中卫市.csv',
 '中山市.csv',
 '临夏回族自治州.csv',
 '临汾市.csv',
 '临沂市.csv',
 '临沧市.csv',
 '丹东市.csv',
 '丽水市.csv',
 '丽江市.csv',
 '乌兰察布市.csv',
 '乌海市.csv',
 '乌鲁木齐市.csv',
 '乐山市.csv',
 '九江市.csv',
 '云浮市.csv',
 '亳州市.csv',
 '伊春市.csv',
 '伊犁哈萨克自治州.csv',
 '佛山市.csv',
 '佳木斯市.csv',
 '保定市.csv',
 '保山市.csv',
 '信阳市.csv',
 '儋州市.csv',
 '克孜勒苏柯尔克孜自治州.csv',
 '克拉玛依市.csv',
 '六安市.csv',
 '六盘水市.csv',
 '兰州市.csv',
 '兴安盟.csv',
 '内江市.csv',
 '凉山彝族自治州.csv',
 '包头市.csv',
 '北京市.csv',
 '北海市.csv',
 '十堰市.csv',
 '南京市.csv',
 '南充市.csv',
 '南宁市.csv',
 '南平市.csv',
 '南昌市.csv',
 '南通市.csv',
 '南阳市.csv',
 '博尔塔拉蒙古自治州.csv',
 '厦门市.csv',
 '双鸭山市.csv',
 '台州市.csv',
 '合肥市.csv',
 '吉安市.csv',
 '吉林市.csv',
 '吐鲁番市.csv',
 '吕梁市.csv',
 '吴忠市.csv',
 '周口市.csv',
 '呼伦贝尔市.csv',
 '呼和浩特市.csv',
 '和田地区.csv',
 '咸宁市.csv',
 '咸阳市.csv',
 '哈密市.csv',
 '哈尔滨市.csv',
 '唐山市.csv',
 '商丘市.csv',
 '商洛市.csv',
 '喀什地区.csv',
 '嘉兴市.csv',
 '嘉峪关市.csv',
 '四平市.csv',
 '固原市.csv',
 '塔城地区.csv',
 '大兴安岭地区.csv',
 '大同市.csv',
 '大庆市.csv',
 '大理白族自治州.csv',
 '大连市.csv',
 '天水市.csv',
 '天津市.csv',
 '太原市.csv',
 '威海市.csv',
 '娄底市.csv',
 '孝感市.csv',
 '宁德市.csv',
 '宁波市.csv',
 '安庆市.csv',
 '安康市.csv',
 '安阳市.csv',
 '安顺市.csv',
 '定西市.csv',
 '宜宾市.csv',
 '宜昌市.csv',
 '宜春市.csv',
 '宝鸡市.csv',
 '宣城市.csv',
 '宿州市.csv',
 '宿迁市.csv',
 '山南市.csv',
 '岳阳市.csv',
 '崇左市.csv',
 '巴中市.csv',
 '巴彦淖尔市.csv',
 '巴音郭楞蒙古自治州.csv',
 '常州市.csv',
 '常德市.csv',
 '平凉市.csv',
 '平顶山市.csv',
 '广元市.csv',
 '广安市.csv',
 '广州市.csv',
 '庆阳市.csv',
 '廊坊市.csv',
 '延安市.csv',
 '延边朝鲜族自治州.csv',
 '开封市.csv',
 '张家口市.csv',
 '张家界市.csv',
 '张掖市.csv',
 '徐州市.csv',
 '德宏傣族景颇族自治州.csv',
 '德州市.csv',
 '德阳市.csv',
 '忻州市.csv',
 '怀化市.csv',
 '怒江傈僳族自治州.csv',
 '恩施土家族苗族自治州.csv',
 '惠州市.csv',
 '成都市.csv',
 '扬州市.csv',
 '承德市.csv',
 '抚州市.csv',
 '抚顺市.csv',
 '拉萨市.csv',
 '揭阳市.csv',
 '攀枝花市.csv',
 '文山壮族苗族自治州.csv',
 '新乡市.csv',
 '新余市.csv',
 '无锡市.csv',
 '日喀则市.csv',
 '日照市.csv',
 '昆明市.csv',
 '昌吉回族自治州.csv',
 '昌都市.csv',
 '昭通市.csv',
 '晋中市.csv',
 '晋城市.csv',
 '普洱市.csv',
 '景德镇市.csv',
 '曲靖市.csv',
 '朔州市.csv',
 '朝阳市.csv',
 '本溪市.csv',
 '来宾市.csv',
 '杭州市.csv',
 '松原市.csv',
 '林芝市.csv',
 '果洛藏族自治州.csv',
 '枣庄市.csv',
 '柳州市.csv',
 '株洲市.csv',
 '桂林市.csv',
 '梅州市.csv',
 '梧州市.csv',
 '楚雄彝族自治州.csv',
 '榆林市.csv',
 '武威市.csv',
 '武汉市.csv',
 '毕节市.csv',
 '永州市.csv',
 '汉中市.csv',
 '汕头市.csv',
 '汕尾市.csv',
 '江门市.csv',
 '池州市.csv',
 '沈阳市.csv',
 '沧州市.csv',
 '河池市.csv',
 '河源市.csv',
 '泉州市.csv',
 '泰安市.csv',
 '泰州市.csv',
 '泸州市.csv',
 '洛阳市.csv',
 '济南市.csv',
 '济宁市.csv',
 '海东市.csv',
 '海北藏族自治州.csv',
 '海南藏族自治州.csv',
 '海口市.csv',
 '海西蒙古族藏族自治州.csv',
 '淄博市.csv',
 '淮北市.csv',
 '淮南市.csv',
 '淮安市.csv',
 '深圳市.csv',
 '清远市.csv',
 '温州市.csv',
 '渭南市.csv',
 '湖州市.csv',
 '湘潭市.csv',
 '湘西土家族苗族自治州.csv',
 '湛江市.csv',
 '滁州市.csv',
 '滨州市.csv',
 '漯河市.csv',
 '漳州市.csv',
 '潍坊市.csv',
 '潮州市.csv',
 '濮阳市.csv',
 '烟台市.csv',
 '焦作市.csv',
 '牡丹江市.csv',
 '玉林市.csv',
 '玉树藏族自治州.csv',
 '玉溪市.csv',
 '珠海市.csv',
 '甘南藏族自治州.csv',
 '甘孜藏族自治州.csv',
 '白城市.csv',
 '白山市.csv',
 '白银市.csv',
 '百色市.csv',
 '益阳市.csv',
 '盐城市.csv',
 '盘锦市.csv',
 '眉山市.csv',
 '石嘴山市.csv',
 '石家庄市.csv',
 '福州市.csv',
 '秦皇岛市.csv',
 '红河哈尼族彝族自治州.csv',
 '绍兴市.csv',
 '绥化市.csv',
 '绵阳市.csv',
 '聊城市.csv',
 '肇庆市.csv',
 '自贡市.csv',
 '舟山市.csv',
 '芜湖市.csv',
 '苏州市.csv',
 '茂名市.csv',
 '荆州市.csv',
 '荆门市.csv',
 '莆田市.csv',
 '菏泽市.csv',
 '萍乡市.csv',
 '营口市.csv',
 '葫芦岛市.csv',
 '蚌埠市.csv',
 '衡水市.csv',
 '衡阳市.csv',
 '衢州市.csv',
 '襄阳市.csv',
 '西双版纳傣族自治州.csv',
 '西宁市.csv',
 '西安市.csv',
 '许昌市.csv',
 '贵港市.csv',
 '贵阳市.csv',
 '贺州市.csv',
 '资阳市.csv',
 '赣州市.csv',
 '赤峰市.csv',
 '辽源市.csv',
 '辽阳市.csv',
 '达州市.csv',
 '运城市.csv',
 '连云港市.csv',
 '迪庆藏族自治州.csv',
 '通化市.csv',
 '通辽市.csv',
 '遂宁市.csv',
 '遵义市.csv',
 '邢台市.csv',
 '那曲市.csv',
 '邯郸市.csv',
 '邵阳市.csv',
 '郑州市.csv',
 '郴州市.csv',
 '鄂尔多斯市.csv',
 '鄂州市.csv',
 '酒泉市.csv',
 '重庆市.csv',
 '重庆市郊县.csv',
 '金华市.csv',
 '金昌市.csv',
 '钦州市.csv',
 '铁岭市.csv',
 '铜仁市.csv',
 '铜川市.csv',
 '铜陵市.csv',
 '银川市.csv',
 '锡林郭勒盟.csv',
 '锦州市.csv',
 '镇江市.csv',
 '长春市.csv',
 '长沙市.csv',
 '长治市.csv',
 '阜新市.csv',
 '阜阳市.csv',
 '防城港市.csv',
 '阳江市.csv',
 '阳泉市.csv',
 '阿克苏地区.csv',
 '阿勒泰地区.csv',
 '阿坝藏族羌族自治州.csv',
 '阿拉善盟.csv',
 '阿里地区.csv',
 '陇南市.csv',
 '随州市.csv',
 '雅安市.csv',
 '青岛市.csv',
 '鞍山市.csv',
 '韶关市.csv',
 '马鞍山市.csv',
 '驻马店市.csv',
 '鸡西市.csv',
 '鹤壁市.csv',
 '鹤岗市.csv',
 '鹰潭市.csv',
 '黄冈市.csv',
 '黄南藏族自治州.csv',
 '黄山市.csv',
 '黄石市.csv',
 '黑河市.csv',
 '黔东南苗族侗族自治州.csv',
 '黔南布依族苗族自治州.csv',
 '黔西南布依族苗族自治州.csv',
 '齐齐哈尔市.csv',
 '龙岩市.csv']
citys = ['七台河市.csv',
 '三亚市.csv',
 '三明市.csv',
 '三沙市.csv',
 '三门峡市.csv']
st = ""
for city0 in citys:
    # load data
    city = city0[0:len(city0)-4]
    st = st + city + " "
with open (road+'/citys.txt', 'w') as file:
    file.write(st)
file.close()
l0 = 0
for city0 in citys:
    # load data
    city = city0[0:len(city0)-4]
    df = pd.read_csv(road+"/{}.csv".format(city),encoding = "utf-8",header=None,dtype={0:str}) 
    df = df[[0,1,14]]
    df.columns = ["统一社会信用代码","qymc","企业性质"]
    df = df[~df["统一社会信用代码"].isna()]
    df = df[~(df["企业性质"] == "个体工商户")]
    df = df[["统一社会信用代码","qymc"]]
    df["qymc"] = df["qymc"].apply(lambda x:normalize(x))
    print(city)
    # 18位统一社会信用代码 -> qyid
    df["qyid"] = df.apply(lambda x:x["统一社会信用代码"][2:4]+x["统一社会信用代码"][8:17],axis = 1)
    # df = df[df["qyid_length"] == 11]
    df0 = df
    df0 = df0[["统一社会信用代码","qymc","qyid"]]
    df0 = df0.drop_duplicates(subset = ["qyid"],keep = "first")
    df0.to_stata("E:/企业数据/税调数据(团队数据)/3 工商_dta（生成qyid）/{}-基本信息.dta".format(city),write_index=False,version = 119)